config/routes.rb
Rails.application.routes.draw do

  root "albums#index"
  get "/albums/new", as: :new_album
  get "/albums/tag/:tag_name" => "albums#tagged", as: :album_tag
  post "/albums" => "albums#create", as: :albums

  post "/albums/:id/vote/:yay_or_nay" => "albums#vote", as: :vote

  get "/contact" => "contact_forms#new", as: :contact
  post "/contacts" => "contact_forms#create", as: :contact_forms
  get "/thanks" => "contact_forms#thanks", as: :thanks

  devise_for :users

end

app/models/album.rb
class Album < ActiveRecord::Base
  acts_as_taggable
  include PgSearch
  pg_search_scope :search,
                  against: [:name, :description],
                  using: {
                    tsearch: {dictionary: "english"}
                  }

  validates :name, :photo, presence: true

  mount_uploader :photo, PhotoUploader

  acts_as_voteable
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "jesse@comal.io",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_voter 
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  scope :for_voter, lambda { |*args| where(["voter_id = ? AND voter_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :for_voteable, lambda { |*args| where(["voteable_id = ? AND voteable_type = ?", args.first.id, args.first.class.base_class.name]) }
  scope :recent, lambda { |*args| where(["created_at > ?", (args.first || 2.weeks.ago)]) }
  scope :descending, lambda { order("created_at DESC") }

  belongs_to :voteable, :polymorphic => true
  belongs_to :voter, :polymorphic => true

  attr_accessible :vote, :voter, :voteable if ActiveRecord::VERSION::MAJOR < 4


  # Comment out the line below to allow multiple votes per user.
  validates_uniqueness_of :voteable_id, :scope => [:voteable_type, :voter_type, :voter_id]
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :authenticate_user!, except: :index

  before_action do
    @tags = ActsAsTaggableOn::Tag.most_used
  end

  def index
    @albums = Album.tally
    @albums = @albums.search(params[:search]) if params[:search].present?
  end

  def tagged
    @albums = Album.tally.tagged_with(params[:tag_name])
    render :index
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(params.require(:album).permit(:name, :photo, :tag_list))
    if @album.save
      redirect_to root_path
    else
      render :new
    end
  end

  def vote
    @album = Album.find(params[:id])
    up_or_down = params[:yay_or_nay]
    if up_or_down == "up"
      current_user.vote_exclusively_for(@album)
    else
      current_user.vote_exclusively_against(@album)
    end
    redirect_to root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController

  def new
    @contact_form = ContactForm.new
  end

  def create
    @contact_form = ContactForm.new(params[:contact_form])
    if @contact_form.valid?
      @contact_form.deliver
      redirect_to thanks_path
    else
      render :new
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/index.html.erb
<div class="row">

<% @albums.each do |album| %>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag album.photo.url(:large), class: "img-responsive" %>
      <div class="caption">
        <h3><%= highlight(album.name, params[:search]) %></h3>
        <p><%= highlight(album.description, params[:search]) %></p>

        <% album.tags.each do |tag| %>
          <%= link_to tag.name, album_tag_path(tag_name: tag.name) %>
        <% end %>


        <p>
          Up: <%=  album.votes_for %><br/>
          Down: <%=  album.votes_against %><br/>
          <%= link_to vote_path(id: album.id, yay_or_nay: "up"), class: "btn btn-primary btn-lg", role: "button", method: :post do%>
            <i class="fa fa-thumbs-up"></i>
          <% end %>


          <%= link_to vote_path(id: album.id, yay_or_nay: "down"), class: "btn btn-default btn-lg", role: "button", method: :post do %>
            <i class="fa fa-thumbs-down"></i>
          <% end %>

        </p>
      </div>
    </div>
  </div>


<% end %>
</div>

<div class="row">
  <h4>Tags</h4>
  <% @tags.each do |tag| %>
    <%= link_to  album_tag_path(tag_name: tag.name), class: "" do %>
      <span class="label label-info">
        <%= tag.name %>
      </span>
      <% end %>&nbsp;
  <% end %>
</div>

app/views/albums/new.html.erb
<div class="page-header">
  <h1>Create new Album</h1>
</div>

<%= simple_form_for @album do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :tag_list, label: "Tags", hint: "eg: yo,yolo,yomama" %>
  <%= f.submit class: "btn btn-lg btn-primary"%>
<% end %>

app/views/contact_forms/new.html.erb
<div class="page-header">
  <h1>Create Us!! <small>We are nice people</small></h1>
</div>

<%= simple_form_for @contact_form do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :message, as: :text %>
  <%= f.submit class: "btn btn-primary btn-lg" %>
<% end %>

app/views/contact_forms/thanks.html.erb
<div class="page-header">
  <h1>Thanks!</h1>
</div>

<p>We'll contact you. promise</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Albumart</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

<nav>
<div class="row">
  <div class="col-xs-8">
    <%= form_tag root_path, method: 'get' do %>
      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search" %>
    <% end %>
  </div>
  <div class="col-xs-4">
    <div class="pull-right">
      <p>

      <%= link_to new_album_path do %>
        <span class="fa-stack fa-lg">
          <i class="fa fa-square-o fa-stack-2x"></i>
          <i class="fa fa-plus fa-stack-1x"></i>
        </span>
      <% end %>

      <%= link_to "Contact Us", contact_path, class: "btn btn-default"%>
    </p>
    </div>
  </div>
</div>
</nav>

<%= yield %>
</div>

</body>
</html>